[ ACI - 24 ] - Lógica para avaliação de particularidades + fluxo
StartSe/Interseas-front pull request #10
Opened 2024-09-13 18:48 UTC by VitorNakagawaL

Adiciona o fluxo de validação de compliance específico para CE MERCANTE x BL Conhecimento; CCT x Conhecimento HAWB e CRT x FATURA COMERCIAL.

2024-09-13 18:49 UTC, samuelpjacobsen commented on flowise-embed/src/components/Bot.tsx
> +      console.log(result);
Remover console.log

2024-09-13 18:50 UTC, samuelpjacobsen commented on flowise-embed/src/components/Bot.tsx
> +      console.log(setLoading);
Remover console.log

2024-09-16 12:54 UTC, IgorBMattiolli requested changes

2024-09-16 12:54 UTC, IgorBMattiolli commented on flowise-embed/src/components/Bot.tsx
>          executeComplianceCheck(filesMapping());
Foi colocado um await no executeComplianceCheck anterior, nao deveria ser colocado outro aqui?

2024-09-16 12:54 UTC, IgorBMattiolli commented on flowise-embed/src/components/Bot.tsx
> +    setLoading(true);
Nos 2 lugares que voce usa funcao ja disparamos setLoading(true), pq disparar novamente? ou mantem fora ou so aqui dentro

2024-09-16 12:54 UTC, IgorBMattiolli commented on flowise-embed/src/utils/pairwiseComparisonUtils.ts
> +      (firstFile.type === DocumentTypes.CCT && secondFile.type === DocumentTypes.CONHECIMENTO_HAWB) ||
Encapsular as condicionais desse if para melhorar a leitura

2024-09-16 12:54 UTC, IgorBMattiolli commented on flowise-embed/src/utils/pairwiseComparisonUtils.ts
> +      console.log('Normal compliance');
Acredito que esse else com o console nao seja necessario

2024-09-16 12:58 UTC, IgorBMattiolli requested changes

2024-09-16 12:58 UTC, IgorBMattiolli commented on flowise-embed/src/utils/pairwiseComparisonUtils.ts
> +export function pairwiseCompareDocuments(
Diminuir a passagem de paramentro 5 parametros para a funcao é muita coisa, ou vc remove ou passa dentro de um objeto

2024-09-18 19:01 UTC, merged