[CI-5] - Implementar a classificação de documentos no front-end
StartSe/Interseas-front pull request #3
Opened 2024-08-28 12:25 UTC by VitorNakagawaL

![image](https://github.com/user-attachments/assets/c6ecff62-b509-41f9-beee-2ab93a8fee15)

2024-08-28 20:51 UTC, samuelpjacobsen approved these changes

2024-08-28 20:58 UTC, vinibs requested changes

2024-08-28 20:58 UTC, vinibs commented on src/components/Bot.tsx
> +        const hasValue = lowerValue !== 'null' && lowerValue !== 'n/a';
Depois de aplicar a sanitização, temos que reavaliar esse trecho - a ideia é que o `hasValue` precise apenas de `lowerValue !== null` depois da sanitização.
O `if` também precisa ser revisto. A ideia é não precisar fazer um if com um novo checklist, e sim formatar o checklist base de acordo com a validação de ter sido ou não encontrado o item do checklist no documento.

2024-08-28 20:58 UTC, vinibs commented on src/components/Bot.tsx
> +      const newFileMap = identifyDocumentType(fileMap);
Nesse caso, as coisas não estão condizentes - você tem uma função que indica retornar o tipo do documento, mas na prática retorna todo o mapeamento do arquivo?
É melhor ajustar para as coisas se corresponderem, seja fazendo passo a passo aqui (identifica o tipo, depois o checklist, valida o checklist, etc.) ou uma função específica para isso.
Acredito que, pelo contexto de o `fileMapping` estar sendo criado aqui, faz mais sentido seus atributos serem definidos aqui também, e não delegados para outra função.

2024-08-28 20:58 UTC, vinibs commented on src/utils/fileClassificationUtils.ts
> +import { FileMapping } from './fileUtils';
Provavelmente esse import não vai ser necessário se fizer a alteração do comentário anterior, mas nos imports, não esquecer de usar a notação do `@` para padronizar.

2024-08-28 20:58 UTC, vinibs commented on src/utils/fileClassificationUtils.ts
> +export const checklistCommercialInvoice = `
Quebrar linha para separar os blocos

2024-08-28 20:58 UTC, vinibs commented on src/utils/fileClassificationUtils.ts
> +};
Como falei no outro comentário, acredito fazer mais sentido criar a lógica de identificação apenas.
Eu separaria em duas funções: uma que recebe o nome do documento e retorna o tipo; outra que recebe o tipo e retorna o checklist.
Aí, lá onde você os chamar, na hora de montar o fileMap, apenas definir os atributos `type` e `checklist` caso de fato haja - caso não, pode deixar `null`.
Verificamos em outro ponto à frente se o checklist foi definido ou não, então é importante manter o comportamento.

2024-08-28 20:58 UTC, vinibs commented on src/utils/jsonUtils.ts
> +  }
Sinto cheirinho de copilot 👀 
Nesse caso, faz mais sentido que o nome seja mais expressivo - um "objeto", em tese, seria um conjunto de chave/valor, não uma string, então essas comparações, a julgar pelo nome, não fazem tanto sentido.
Que tal deixar o nome das variáveis mais explícito?

2024-08-30 11:35 UTC, vinibs commented on src/components/Bot.tsx
> -        console.error(error);
Manter o console.error pro casos dos catch

2024-08-30 11:35 UTC, vinibs commented on src/components/Bot.tsx
> -
Manter a quebra de linha

2024-08-30 11:35 UTC, vinibs commented on src/components/Bot.tsx
> +        checklistItem += (hasValue ? `:<br>${multiSpaces}${value}` : `:<br>${multiSpaces}N/A`) + '<br>';
Nesse caso, como todos os casos vão ter `:<br>`, faz sentido esse trecho ser movido para a linha 1095 ao invés de ser incluído dos dois lados do ternário

2024-08-30 11:35 UTC, vinibs commented on src/utils/jsonUtils.ts
> +  return keyValue === 'n/a' || keyValue === 'null' || keyValue === 'undefined' || keyValue === '';
Nesse caso você poderia simplificar a lógica:
```
  return ['n/a', 'null', 'undefined', ''].includes(keyValue.toLowerCase())
```

Não esquecer de validar o valor após converter pra lowercase, senão o N/A (em maiúsculas) vai passar batido.

2024-08-30 14:01 UTC, vinibs commented on src/utils/jsonUtils.ts
> +      sanitizeJson(keyValue);
Ainda segue a dúvida: no caso de ser um objeto, você chama a função recursivamente, mas não utiliza o retorno dela pra nada. Chegou a testar esse caso?

2024-08-30 16:48 UTC, vinibs approved these changes

2024-08-30 19:26 UTC, vinibs approved these changes

2024-08-30 19:26 UTC, merged