[ACI-28] - Atualizar identidade visual para nova marca
StartSe/Interseas-front pull request #32
Opened 2024-10-04 15:00 UTC by luislimaAI

Foi realizado as mudanças de layout no front-end:
- Troca da cor base
- Troca de ícone do bot
- Troca de ícone do popup de upload de documentos
- Troca de cor de fundo das mensagens do bot
- Troca de ícone de loading
- Troca da cor dos ícones de checklist
- Adicionado logo marca no projeto

![Captura de Tela 2024-10-04 às 09 46 31](https://github.com/user-attachments/assets/f19866ff-3350-448e-ac33-dfde9c4aa699)
![Captura de Tela 2024-10-04 às 09 46 08](https://github.com/user-attachments/assets/8553a0b2-38fe-4c86-96bb-5b6dc23e810b)
![Captura de Tela 2024-10-04 às 09 45 33](https://github.com/user-attachments/assets/85349ccd-8127-418b-9e1b-9d77d3c9cfdb)

2024-10-04 17:11 UTC, rnatto-gempe requested changes
🚀 🚀 🚀 🚀 🚀

2024-10-04 17:11 UTC, rnatto-gempe commented on flowise-embed/src/features/full/components/Full.tsx
> +            bubbleBackgroundColor={defaultColor}
vamos priorizar por alterar a paleta de cores pelo tema, mantendo o uso do `props.theme`

2024-10-04 17:11 UTC, rnatto-gempe commented on flowise-embed/src/features/bubbleCriticalAnalysis/components/Bubble.tsx
> +              bubbleBackgroundColor={defaultColor}
manter o uso do `props.theme`

2024-10-04 17:11 UTC, rnatto-gempe commented on flowise-embed/src/features/bubble/components/BubbleButton.tsx
> +          'background-color': defaultButtonColor,
manter o uso do `props`

2024-10-04 17:11 UTC, rnatto-gempe commented on flowise-embed/src/components/Bot.tsx
> +        const checkboxStyle = hasValue ? 'color: white; background-color: background: #136FEE; ' : '';
aqui também é preferível que consigamos importar as cores do tema, para permitir estilizar todo o projeto com o mesmo processo

2024-10-04 17:11 UTC, rnatto-gempe commented on flowise-embed/src/components/TypingBubble.tsx
> +    <svg class="animate-spin" width="55" height="54" viewBox="0 0 55 54" fill="none" xmlns="http://www.w3.org/2000/svg">
tenho uma ressalva de utilizarmos este loading como loading principal para todo o processo. Vamos validar com design, mas acredito que o propósito do loading com spinner seja apenas para a avaliação de arquivos antes da IA se posicionar no chat. Para aguardar mensagens do chat, fora do processo de checklist e de compliance por exemplo, sugiro utilizarmos o dot loading ainda. Mas podemos mergear e avaliar a experiência com o @tpgo23

2024-10-04 17:14 UTC, samuelpjacobsen commented on flowise-embed/src/components/Badge.tsx
> +            padding: '0 12px',
Não seria melhor colocar pra rem? como o vini tinha sugerido?

2024-10-04 17:14 UTC, samuelpjacobsen commented on flowise-embed/src/components/BadgeAnalise.tsx
> +            padding: '0 12px',
Não seria melhor colocar pra rem? como o vini tinha sugerido?

2024-10-04 17:16 UTC, samuelpjacobsen commented on flowise-embed/src/components/Bot.tsx
> +        fileMap.type = 'Documento sem checklist';
não seria uma boa passar pelo utils de mensagem?

2024-10-04 17:18 UTC, samuelpjacobsen commented on flowise-embed/src/components/bubbles/LoadingBubble.tsx
> +        padding: '16px',
Não seria melhor colocar pra rem? como o vini tinha sugerido?

2024-10-04 17:22 UTC, samuelpjacobsen commented
Muito bom =)
Mas sugeri algumas alteraçoes

2024-10-04 17:29 UTC, samuelpjacobsen requested changes
Coisa pouca

2024-10-09 12:39 UTC, samuelpjacobsen approved these changes

2024-10-09 15:24 UTC, vinibs requested changes

2024-10-09 15:24 UTC, vinibs commented on flowise-embed/src/components/Badge.tsx
> +            padding: '0 0.75rem',
Que tal mover esses estilos pra uma classe?

2024-10-09 15:24 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +        fileMap.type = messageUtils.DOCUMENT_WITHOUT_CHECKLIST_MESSAGE;
Não entendi o por quê de aqui estar associando um tipo de documento a uma mensagem 🤔

2024-10-09 15:24 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +        checklistItem += hasValue ? spacedText(value) : spacedText(`N/A`);
O `N/A` foi substituído por "N/I" ou "Não identificado", não?

2024-10-09 15:24 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +                    )}
Se o que muda é apenas o typeLoading baseado na `uploading()`, você não precisa fazer 4 ifs - pode manter os 2 originais e usar uma variável de estado mapeando o `typeLoading` desejado baseado no valor da `uploading()`.

2024-10-09 15:24 UTC, vinibs commented on flowise-embed/src/components/BotCriticalAnalysis.tsx
> +    let criticalAnalysisItem = `<input type="checkbox" ${hasValue ? 'checked' : ''} disabled><span></span> <b>${key}</b>:<br>`;
Por quê do trecho `<span></span>`?

2024-10-09 15:24 UTC, vinibs commented on flowise-embed/src/components/BotCriticalAnalysis.tsx
> +                    )}
Mesma sugestão sobre o typeLoading, apesar de ser no arquivo que será removido (então esse pode ser ignorado).

2024-10-09 15:24 UTC, vinibs commented on flowise-embed/src/components/bubbles/LoadingBubble.tsx
> +            'border-radius': '0.375rem',
Esse conjunto de estilos também pode ser movido para uma classe.

2024-10-10 14:35 UTC, samuelpjacobsen approved these changes

2024-10-10 15:31 UTC, vinibs commented on flowise-embed/src/components/bubbles/LoadingBubble.tsx
> +};
Dá pra otimizar um pouco esse código.
Como você tem um `if { return }`, não precisa do `else`;
O que é a div dentro do `else` e fora do return?
Se o trecho
```
<div class="flex flex-row justify-start mb-2 items-start host-container" style={{ 'margin-right': '50px' }}>
        <Avatar />
        ...
</div>
```
É comum a ambos os casos, não precisa ser repetido dentro do if, pode estar por fora.
Por exemplo:
```suggestion
const loadingTypes = {
  'upload': (
      <div class=" flex justify-start mb-2 items-center animate-fade-in host-container">
          <span class="px-4 py-4 ml-2 whitespace-pre-wrap max-w-full chatbot-host-bubble" data-testid="host-bubble">
            <UploadingBubble />
          </span>
      </div>
    ),
  'typing': (
      <div
          style={{
            'border-radius': '0.375rem',
          }}
          class="flex justify-start mb-2 items-center animate-fade-in host-container"
        >
          <span class="px-4 py-4 ml-2 whitespace-pre-wrap max-w-full chatbot-host-bubble" data-testid="host-bubble">
            <TypingBubble />
          </span>
        </div>
  ),
};

return (
  <div class="flex flex-row justify-start mb-2 items-start host-container" style={{ 'margin-right': '50px' }}>
    <Avatar />
    {loadingTypes[typeLoading]}
  </div>
);
```

Assim, você corta o if e tem flexibilidade para caso precise alternar entre mais tipos de loading no futuro.
Não testei se funciona, pode precisar de alguns ajustes, mas a ideia é mais ou menos essa.

2024-10-10 15:32 UTC, vinibs commented on flowise-embed/src/utils/messageUtils.ts
> +  NEW_CHAT_BUTTON_LABEL: 'Novo documento',
Considerando que é a mensagem de "novo chat", não deveria ser "novo chat" o texto? Por que foi alterado para "novo documento"? 🤔

2024-10-10 16:52 UTC, luislimaAI commented on flowise-embed/src/utils/messageUtils.ts
> +  NEW_CHAT_BUTTON_LABEL: 'Novo documento',
Dá pra mudar o nome de chat pra Document, alterei o chat que foi a alteração do figma.

2024-10-10 17:30 UTC, vinibs approved these changes

2024-10-10 18:25 UTC, merged