[ACI - 13] -  Envio de alertas no compliance
StartSe/Interseas-front pull request #6
Opened 2024-09-05 14:20 UTC by VitorNakagawaL

TASK PARA ADIÇÃO DE VALIDAÇÕES PRÉ COMPLIANCE INDICANDO FALTA DE DOCUMENTOS REFERENTES A LICENÇAS DE IMPORTAÇÃO; MÁQUINAS OU EQUIPAMENTOS IMPORTADOS E A PRESENÇA DE EX-TARIFÁRIO.

[Agentflow](https://interseas-flowise.paas.startse.com/agentcanvas/77a8ed32-b99a-4739-939e-e8a02d0f3d4e)

#PROMPT DE EXTRAÇÃO VIA CHECKLIST:
Você fará o papel de um OCR. Apenas extraia o texto da imagem e retorne exatamente como está descrito no arquivo.

- Você receberá um CHECKLIST, cujos itens podem estar em um idioma diferente dos dados presentes na imagem anexada.

- Traga os dados encontrados no CHECKLIST, no formato key-value pair.

- Quando um item do CHECKLIST contiver alguma informação entre parênteses ou após um hífen, considere-a como informação adicional para encontrar o dado necessário, mas não inclua o conteúdo entre parênteses na resposta. 
Siga a formatação conforme os exemplos a seguir: 
* Se estiver escrito  "exportador (nome, CNPJ)", na saída apresente apenas "exportador", seguido do valor encontrado
* Se estiver escrito "código (no formato CD-<número>)", na saída apresente apenas "código", seguido do valor encontrado.
* Se estiver escrito "importador - também chamado de buyer", na saída apresente apenas "importador", seguido do valor encontrado.
No caso de a informação entre parênteses ser uma condicional, considere-a para decidir se esse item deve ser exibido na resposta ou não:
* Se estiver escrito "frete (se prepaid)", mas constatou-se que não se trata de um prepaid, a saída não deve trazer o item.
* Valores de "true" e "false" devem ser retornados como strings, com aspas.

- A resposta deve ser separada em seções - deve conter uma primeira seção "checklist", na qual cada item do CHECKLIST deve ser trazido; e, caso o CHECKLIST apresente "conferências:", seguido de uma lista de itens, a resposta deve conter uma segunda seção "conferências", o acento não pode ser esquecido.

- Sempre formate a resposta final em um JSON de linha única para correlacionar as chaves e valores. Nunca utilize formatação Markdown. Certifique-se de que não haja espaços ou quebras de linha entre os elementos do objeto na resposta final.

- Se um item do CHECKLIST não for encontrado na imagem, deixe seu valor como "null" no JSON final.

- Se dentro de um CHECKLIST que já possui conferências, for encontrado o inicio de outra seção de mesmo nome, retirar o titulo e manter os itens do checklist.

- Na seção "conferências" deve constar a relação de itens conferidos de acordo com a conferência ter sido bem-sucedida ou não. Coloque à frente de cada item conferido a relação dos valores avaliados.

- Caso o CHECKLIST não contenha o trecho "conferências:", seguido de uma lista de itens, não traga a seção "conferências" na resposta.

- Para informar se o documento contém assinatura ou carimbo, responda "true" ou "false".

- Quando houver o atributo "error", não inclua mais nenhum outro atributo na saída.

#PROMPT DE EXTRAÇÃO DEFAULT

Você fará o papel de um OCR. Apenas extraia o texto da imagem e retorne exatamente como está descrito no arquivo.

- Traga TODOS os dados encontrados na imagem que sejam possíveis de relacionar no formato key-value pair.

- Sempre formate a resposta final em um JSON de linha única para correlacionar as chaves e valores. Nunca utilize formatação Markdown. Certifique-se de que não haja espaços ou quebras de linha entre os elementos do objeto na resposta final.

- Valores de "true" e "false" devem ser retornados como booleanos, com aspas.

- A resposta deve ser separada em seções - deve conter uma primeira seção "checklist", na qual cada item encontrado no formato key-value-pair deve ser trazido; E  "conferências:", seguido de uma lista de itens, a resposta deve conter uma segunda seção "conferências", o acento não pode ser esquecido.

Conferências necessárias:
  • Máquina/Equipamento - Verificar se o item é máquina ou equipamento (true/false)
  • Possui Ex-tarifário - Procurar dados começados com "EX", "EX[número]" (true/false)

  - Caso identifique a presença de assinatura ou carimbo na imagem, responda "true" ou "false" à respectiva chave para o item em questão.

- Quando houver o atributo "error", não inclua mais nenhum outro atributo na saída.

- Responda uma lista com todos os itens encontrados na imagem. Cada item deve estar um em cada linha, utilizando o formato chave-valor, em que a chave é escrita em negrito, seguida de dois pontos e o valor associado.

2024-09-05 17:10 UTC, luislimaAI commented on flowise-embed/dist/utils/messageUtils.d.ts
> +    CHECK_EX: string;
O que seria esse CHECK_EX? Esse nome reflete do que se trata a mensagem? Pensando no padrão das outras variáveis.

2024-09-05 17:10 UTC, luislimaAI commented on flowise-embed/src/utils/messageUtils.ts
> +  CHECK_EX: 'Atenção, comparare se a descrição referente está conforme a plataforma do EX-tarifário',
Mesmo caso do comentário anterior

2024-09-05 17:40 UTC, VitorNakagawaL commented on flowise-embed/dist/utils/messageUtils.d.ts
> +    CHECK_EX: string;
Era pra chegar a questão Ex tarifário, mas vou reformular um nome pra um mais expressivo

2024-09-05 17:40 UTC, VitorNakagawaL commented on flowise-embed/src/utils/messageUtils.ts
> +  CHECK_EX: 'Atenção, comparare se a descrição referente está conforme a plataforma do EX-tarifário',
Era pra chegar a questão Ex tarifário, mas vou reformular um nome pra um mais expressivo

2024-09-05 17:50 UTC, samuelpjacobsen commented
Eu ia comentar da variavel tambem, mas o luis ja avisou rsrs =).

2024-09-05 17:50 UTC, samuelpjacobsen approved these changes

2024-09-05 19:36 UTC, vinibs requested changes

2024-09-05 19:36 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +    console.log(props.chatflowid, props.apiHost, body);
Remover console.log

2024-09-05 19:36 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +        setMessages((prevMessages) => [...prevMessages, { message: messageUtils.CHECK_EX_TARIFF, type: 'apiMessage' }]);
Atualizar a variável `conferencias` para o termo em inglês, mantendo a padronização das nomenclaturas.
Além disso, os valores booleanos vêm sempre como string?
Existe opção de virem diretamente como booleanos?
Existe possibilidade de virem com outra configuração de letras maiúsculas (tipo "True", "TRUE" etc.)?

Além disso, adicionar uma linha em branco para separar o `setMessages` da `const` logo abaixo.

2024-09-05 19:36 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +  }
Onde entra a lógica para o EX?
Além disso, é melhor mover essa função para um arquivo à parte, como um utils.

2024-09-05 19:36 UTC, vinibs commented on flowise-embed/src/utils/fileClassificationUtils.ts
> +export const conferenciasDefault = `
Renomear para manter o padrão de nomenclaturas em inglês.

2024-09-05 19:36 UTC, vinibs commented on index.html
Essa alteração não deveria ser incluída no commit, dado que altera o fluxo base com o qual a aplicação se comunica.
As aspas duplas foram alteradas manualmente ou foi o linter? Se foi o linter, é curioso - já que outros trechos ficaram com aspas simples 🤔

2024-09-05 19:36 UTC, vinibs commented on flowise-embed/src/utils/messageUtils.ts
> +  CHECK_EX_TARIFF: 'Atenção, compare se a descrição referente está conforme a plataforma do EX-tarifário',
Pode manter as linhas em branco separando as mensagens. A ideia é utilizar as linhas em branco para separar os blocos de contexto (labels de botões, mensagens ao usuário, erros etc.).
Além disso, seguindo os comentários dos meninos, o nome da `CHECK_EX_TARIFF` pode ser mais explícito. Que tal `EX_TARIFF_CHECK_ALERT_MESSAGE`?
Nessa mesma pegada, poderia atualizar o nome da linha 14 para `IMPORT_LICENSE_NOT_FOUND_ALERT_MESSAGE`, criando assim um novo "subgrupo" de mensagens, o das mensagens de alerta - e poderia separá-lo dos demais por uma nova linha em branco.

2024-09-05 19:51 UTC, VitorNakagawaL commented on index.html
Ocorreu uma confusão, não reparei no padrão, mudei de agentflow algumas vezes

2024-09-05 19:51 UTC, luislimaAI approved these changes

2024-09-05 20:19 UTC, VitorNakagawaL commented on flowise-embed/src/components/Bot.tsx
> +        setMessages((prevMessages) => [...prevMessages, { message: messageUtils.CHECK_EX_TARIFF, type: 'apiMessage' }]);
A questão do booleano vir como string, é que percebi que alucinava menos nas resposta. Por exemplo, se eu pedir que venha sempre booleano, a taxa de erro é maior pois ele prefere retornar como string. Já quando coloco para retornar como string, pelo menos nos vários testes, acabei percebendo que é mais vantajoso e confiavel.

2024-09-05 20:24 UTC, VitorNakagawaL commented on flowise-embed/src/components/Bot.tsx
> +  }
A lógica do ex está sendo feita a cada envio de documento
```
if (conferences['Máquina/Equipamento'] === 'true' || conferences['Possui Ex-tarifário'] === 'true') {
        setMessages((prevMessages) => [...prevMessages, { message: messageUtils.EX_TARIFF_CHECK_ALERT_MESSAGE, type: 'apiMessage' }]);
      }
```

2024-09-09 11:04 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +        setMessages((prevMessages) => [...prevMessages, { message: messageUtils.CHECK_EX_TARIFF, type: 'apiMessage' }]);
Certo.
Por via das dúvidas, que tal colocar um `.toLowerCase()` para garantir os caracteres em caixa baixa para a comparação com `true`?

2024-09-09 11:12 UTC, vinibs commented on flowise-embed/src/utils/complianceUtils.ts
> +import { FileMapping } from './fileUtils';
Usar o import com o `@`.

2024-09-09 11:12 UTC, vinibs commented on flowise-embed/src/utils/messageUtils.ts
> +  EX_TARIFF_CHECK_ALERT_MESSAGE: 'Atenção, compare se a descrição referente está conforme a plataforma do EX-tarifário',
Acrescentar uma quebra de linha antes do `EX_TRARIFF_CHECK_ALERT_MESSAGE`

2024-09-09 11:12 UTC, vinibs commented on index.html
> +          chatflowid: '77a8ed32-b99a-4739-939e-e8a02d0f3d4e',
Esse código ainda não corresponde ao fluxo de produção. Se fizermos o merge dessa forma, passaremos a apontar para o fluxo errado - precisamos atualizar o que for necessário no fluxo de produção antes, também.
Temos que validar as alterações no fluxo antes de fazer o merge.

2024-09-09 14:48 UTC, vinibs approved these changes

2024-09-09 14:50 UTC, merged