[ACI-102] Menu com histórico de chats
StartSe/Interseas-front pull request #73
Opened 2024-11-21 14:02 UTC by Wes-startse

Desenvolver, no menu, a seção de histórico de chats conforme o Figma.

As funções de obter os chats, renomear e excluir, relacionadas ao banco, foram desenvolvidas na task [Suporte ao histórico de chats](https://startse.atlassian.net/browse/ACI-101.)

Adicionar ao menu:

Listagem de chats do tipo de fluxo atualmente aberto na tela (compliance, análise crítica, estimativa de custos)

Cada chat deve ter a opção de ser renomeado e excluído

Para novos chats, sem um título definido, exibir no menu “Sem título - <dd/mm/yyyy HH:MM>”

2024-11-21 14:07 UTC, samuelpjacobsen commented on flowise-embed/src/features/menu/components/Menu.tsx
> +      const offset = -3 * 60; // UTC-3 in minutes
Levando em conta o nome da const adjustToBrazilTime, acho irrelevante o comentário

2024-11-21 14:08 UTC, samuelpjacobsen commented on flowise-embed/src/features/menu/components/Menu.tsx
> +    // Sort chatItems by created_at in descending order
Aqui a mesma situação, da pra entender sem o comentário

2024-11-21 14:09 UTC, samuelpjacobsen commented on flowise-embed/src/features/menu/components/Menu.tsx
> +      // Zero out hours, minutes, seconds, and milliseconds for day comparison
essa parte também

2024-11-21 14:10 UTC, samuelpjacobsen commented
Resolvendo os comentários, ficou mto top =)

2024-11-21 14:19 UTC, Daniela-startse approved these changes

2024-11-21 15:10 UTC, vinibs commented on flowise-embed/src/features/menu/components/Menu.tsx
> +      const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
Aqui também, evitar números mágicos. É chato, mas é uma boa deixar tudo bem claro:
```suggestion
      const hoursInDay = 24;
      const minutesInHour = 60;
      const secondsInMinute = 60;
      const millisecondsInSecond = 1000;
      const millisecondsInDay = millisecondsInSecond * secondsInMinute * minutesInHour * hoursInDay;
      const diffDays = Math.ceil(diffTime / millisecondsInDay);

2024-11-21 15:10 UTC, vinibs commented on flowise-embed/src/features/menu/components/Menu.tsx
> +      }
Aqui entra a lógica que comentei ao fazer um objeto com todas as informações:
```suggestion
      if ((!currentGroup.minDaysDiff || diffDays >= currentGroup.minDaysDiff) && (!currentGroup.maxDaysDiff || diffDays <= currentGroup.maxDaysDiff)) {
        currentGroup.items.push(item);
```

Lembrando que pra isso você precisaria ter um `currentGroup`, de modo que quando você identificar que o grupo atual não serve mais, você passa a olhar para o próximo.
Podemos trocar uma ideia a respeito, se quiser.

2024-11-21 15:10 UTC, vinibs commented on flowise-embed/src/features/menu/components/Menu.tsx
> +    return { groups, labels };
E com a alteração da estrutura, você só precisaria retornar o objeto de grupos, que já teria tudo nele.

2024-11-21 15:10 UTC, vinibs commented on flowise-embed/src/features/menu/components/Menu.tsx
> +      fetchChatIds();
Há a necessidade de fazer o fetch novamente toda vez que o nome de um chat for atualizado?

2024-11-21 15:10 UTC, vinibs commented on flowise-embed/src/features/menu/components/Menu.tsx
> +                {/* <button>+Novo Chat</button> */}
Pode remover o trecho comentado

2024-11-21 15:10 UTC, vinibs commented on flowise-embed/src/features/menu/components/Menu.tsx
> +                                      <input type="text" name="chatNameField" id={item.id} value={formatDateChat(item)} onInput={handleInputChange} />
o atributo `name` pode receber um valor como "chat-name", nesse caso, seguindo o padrão de nomenclaturas de HTML e CSS (e simplificando um pouco)

2024-11-21 16:51 UTC, VitorNakagawaL requested changes

2024-11-21 16:51 UTC, VitorNakagawaL commented on flowise-embed/src/features/menu/components/DeleteModal.tsx
> +                cancelar
Seria interessante jogar essas mensagens de texto para o messageUtils para seguir o padrão.

2024-11-21 16:51 UTC, VitorNakagawaL commented on flowise-embed/src/features/menu/components/Menu.tsx
> +    } else if (currentFlow() === 'critical_analysis') {
Aqui poderíamos usar os ENUMS de flow que temos no projeto para ficar no padrãozin, algo como:
`if (props.flow === Flow.CriticalAnalysis.toString())`

2024-11-21 18:20 UTC, Wes-startse commented on flowise-embed/src/features/menu/components/Menu.tsx
> +    setSelectedChatName(chatName);
Nesse caso Vini, é devido a utilização do ChatName dentro do Modal delete, ai quando eu abro o modal, já trago o id e o chatName.
![image](https://github.com/user-attachments/assets/d60550c9-3c0a-4af2-859e-b3fc58412b04)

2024-11-25 11:47 UTC, matheusmondaini-startse approved these changes

2024-11-25 12:23 UTC, luislimaAI approved these changes

2024-11-25 15:05 UTC, vinibs commented on flowise-embed/src/features/menu/components/Menu.tsx
> +                                  {editingChatId() === item.id && editingChatId() !== null ? (
Você também pode simplificar essa condição fazendo algo como 
`{editingChatId() && editingChatId() === item.id ? (` ou 
`{!!editingChatId() && editingChatId() === item.id ? (`,
dado que um id nunca vai ser 0, sobrando apenas o null (e o false) pra verificar (o que dá quase na mesma), então não precisaria ser específico ao ponto de precisar do `=== null`

2024-11-25 15:06 UTC, vinibs approved these changes

2024-11-27 11:43 UTC, VitorNakagawaL approved these changes

2024-11-27 12:08 UTC, samuelpjacobsen approved these changes

2024-11-27 12:25 UTC, merged