[ACI-107] - [Compliance] Atualizar checklists
StartSe/Interseas-front pull request #80
Opened 2024-11-29 14:24 UTC by VitorNakagawaL

2024-11-29 14:39 UTC, Daniela-startse approved these changes

2024-11-29 14:40 UTC, luislimaAI approved these changes

2024-11-29 17:17 UTC, samuelpjacobsen approved these changes

2024-12-02 19:57 UTC, matheusmondaini-startse approved these changes

2024-12-04 17:48 UTC, luislimaAI commented on flowise-embed/src/utils/fileClassificationUtils.ts
> +    console.log(checklistTypeMapping[documentType as keyof typeof checklistTypeMapping]);
Remover console log

2024-12-04 17:54 UTC, Daniela-startse approved these changes

2024-12-04 17:59 UTC, Wes-startse approved these changes

2024-12-04 18:01 UTC, samuelpjacobsen requested changes
Era pra ter a dist mesmo?

2024-12-04 18:40 UTC, samuelpjacobsen approved these changes

2024-12-05 13:58 UTC, vinibs commented on flowise-embed/src/components/Bot.tsx
> +        }
Aqui tem alguns pontos para serem observados:
- Sugiro mover a expressão regular para uma constante, de modo a deixar claro sobre o que se refere a regex
- Quem/o quê seria `value` aqui nesse trecho? (Olhando apenas pelo trecho realçado pelo GitHub, não fica claro e é um termo um tanto quanto genérico)
- Pode mover essas mensagens para a util de mensagens do projeto

2024-12-05 13:58 UTC, vinibs commented on flowise-embed/src/utils/fileClassificationUtils.ts
> +• Importação por Conta e Ordem - (Deve retornar true apenas se Adquirente for diferente ao Importador)
Seria necessário adicionar a instrução de sempre retornar `true` e `false` ou a IA já entende quando executa como está?

2024-12-05 13:58 UTC, vinibs commented on flowise-embed/src/utils/fileClassificationUtils.ts
> +• Cubagem (m³)
Faria sentido indicar `m³/m3`, dado que alguns documentos utilizam a notação `m3`? Ou a IA já interpreta corretamente esses casos?

2024-12-05 13:58 UTC, vinibs commented on flowise-embed/src/utils/fileClassificationUtils.ts
> +• Cubagem total (m³)
Mesma questão do `m3`, se achar relevante.
Também se aplica às demais ocorrências.

2024-12-05 17:51 UTC, matheusmondaini-startse approved these changes

2024-12-09 13:09 UTC, vinibs commented on flowise-embed/src/utils/fileClassificationUtils.ts
> +• Importação por Conta e Ordem - (Deve retornar true apenas se o Adquirente for igual ao importador, se não, false)
Aqui não deveria ser diferente?

2024-12-09 13:09 UTC, vinibs commented on flowise-embed/src/utils/fileClassificationUtils.ts
> +• Importação por Conta e Ordem - (Deve retornar true apenas se Destinatário ou Consignatário, se não, false)`;
Essa descrição parece que ficou incompleta

2024-12-09 15:00 UTC, merged